#!/usr/bin/env python3

import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CompressedImage

def cbImage(msg):
    cv_image = cv.imgmsg_to_cv2(msg, "bgr8")
    pub_img.publish(cv.cv2_to_compressed_imgmsg(cv_image, "jpg"))

if __name__ == '__main__':
    rospy.init_node('image_raw2compressed')
    rospy.Subscriber('/camera/image', Image, cbImage, queue_size=1)
    pub_img = rospy.Publisher('/camera/image/compressed', CompressedImage, queue_size=1)
    cv = CvBridge()
    rospy.spin()
